# Generated by Django 5.2.5 on 2025-09-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_rename_debt_reservation_expected_agency_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='total_pending_balance',
        ),
        migrations.AddField(
            model_name='reservation',
            name='costumer_document',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='type_document',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
