# Generated by Django 5.2.5 on 2025-09-07 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['tour_name'], 'verbose_name': 'Tour', 'verbose_name_plural': 'Tours'},
        ),
        migrations.AlterModelOptions(
            name='tourschedule',
            options={'ordering': ['-date', 'start_time'], 'verbose_name': 'Horario de tour', 'verbose_name_plural': 'Horarios de tours'},
        ),
        migrations.AlterUniqueTogether(
            name='tourschedule',
            unique_together={('tour', 'date', 'start_time')},
        ),
        migrations.AddField(
            model_name='tour',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='tour',
            name='default_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de inicio por defecto'),
        ),
        migrations.AddField(
            model_name='tourschedule',
            name='opened',
            field=models.BooleanField(default=True, verbose_name='Abierto'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio base'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='default_capacity',
            field=models.PositiveIntegerField(verbose_name='Capacidad por defecto'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre del tour'),
        ),
        migrations.AlterField(
            model_name='tourschedule',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='Capacidad'),
        ),
        migrations.AlterField(
            model_name='tourschedule',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='tourschedule',
            name='start_time',
            field=models.TimeField(verbose_name='Hora de inicio'),
        ),
        migrations.AlterField(
            model_name='tourschedule',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reservations.tour', verbose_name='Tour'),
        ),
        migrations.RemoveField(
            model_name='tourschedule',
            name='status',
        ),
    ]
