# Generated by Django 5.2.5 on 2025-10-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_remove_reservation_total_pending_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
