# Generated by Django 5.2.5 on 2025-10-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='costumer_document',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
