# Generated by Django 5.2.5 on 2025-10-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_reservation_costumer_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='nit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
