# Generated by Django 5.2.5 on 2025-10-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_agency_nit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='nit',
            new_name='tax_id',
        ),
    ]
